version: '3.1'

services:

  wordpress:
    image: wordpress
    container_name: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db-wp
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - phpmyadmin
    volumes:
      - wordpress:/var/www/html

  db-wp:
    container_name: db-wp
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db-wp
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db-wp
      MYSQL_USER: root
      MYSQL_PASSWORD: wordpress

volumes:
  wordpress:
  db:
